@startuml Create team request
allowmixing

agent "POST request \nURI: /api/teams"
  json "CreateTeam" as J {
    "name": "string",
    "competitionId": "number"
  }

"POST request \nURI: /api/teams" -> J 
@enduml