@startuml Create tournament request
allowmixing

agent "URI: /join_tournament"
stack {
  json "Join tournament interface" as J {
    "invite_code": "string",
    "user_team_id": "int"
  }
}

"URI: /join_tournament" -> J 
@enduml