@startuml Login request
allowmixing

agent "POST request \nURI: /api/authentication/login"
  json "Login" as J {
    "emailOrusername": "string",
    "password": "string"
  }

"POST request \nURI: /api/authentication/login" -> J 
@enduml