@startuml Register user request
allowmixing

agent "URI: /register"
stack {
  json "Register user interface" as J {
    "username": "string",
    "email": "string",
    "password": "string"
  }
}

"URI: /register" -> J 
@enduml