@startuml Register request
allowmixing

agent "POST request \nURI: /api/users/register"
  json "RegisterUser" as J {
  "username": "string",
  "email": "string",
  "password": "string"
  }

"POST request \nURI: /api/users/register" -> J 
@enduml