@startuml User
skinparam Linetype Ortho

package UserAggregate <<Rectangle>> {
    class User <<AggregateRoot>> {
        +int Id
        +string UserName
        +string Email
        +SecurityInfo SecurityInfo
    }

    class SecurityInfo <<ValueObject>> {
        +string Salt
    }

    User *- "1" SecurityInfo 
}
@enduml 