@startuml Authentication token response
allowmixing

agent "GET response \nURI: /api/authentication/login"
  json "AuthenticationToken" as J {
    "token": "string",
    "tokenType": "string",
    "expiresIn": "number"
  }

"GET response \nURI: /api/authentication/login" -> J 
@enduml