@startuml Get bulletin response
allowmixing

agent "GET response \nURI: /api/tournaments/{tournamentId}/bulletins"
  json "Bulletin" as J {
    "id": "number",
    "text": "string",
    "createdTime": "string",
    "lastEditedTime": "string",
    "userId": "number",
    "username": "string"
  }

"GET response \nURI: /api/tournaments/{tournamentId}/bulletins" -> J 
@enduml