@startuml Get point match response
allowmixing

agent "GET response \nURI: /api/points/matches/{matchId}"
  json "PointMatch" as J {
    "playerName": "string",
    "clubName": "string",
    "pointCategoryName": "string",
    "occurrences": "number",
    "totalPoints": "number"
  }

"GET response \nURI: /api/points/matches/{matchId}" -> J 
@enduml