@startuml Get point team response
allowmixing

agent "GET response \nURI: /api/points/teams/{teamId}"
  json "PointTeam" as J {
    "playerName": "string",
    "clubName": "string",
    "pointCategoryName": "string",
    "pointAmount": "number",
    "occurrences": "number",
    "totalPoints": "number"
  }

"GET response \nURI: /api/points/teams/{teamId}" -> J 
@enduml