@startuml Get team point response
allowmixing

agent "GET response \nURI: /api/teams/{teamId}/points"
  json "TeamPoint" as J {
    "playerName": "string",
    "clubName": "string",
    "pointCategoryName": "string",
    "occurrences": "number",
    "totalPoints": "number"
  }

"GET response \nURI: /api/teams/{teamId}/points" -> J 
@enduml