@startuml Get tournament details response
allowmixing

agent "GET response \nURI: /api/tournaments/{tournamentId}"
  json "TournamentDetails" as J {
    "id": "number",
    "name": "string",
    "description": "string",
    "inviteCode": "string",
    "competitionId": "number",
    "competitionName": "string",
    "ownerUsername": "string",
    "ownerUserId": "number"
  }

"GET response \nURI: /api/tournaments/{tournamentId}" -> J 
@enduml