@startuml Get team response
allowmixing

agent "GET response \nURI: /api/teams/{teamId}"
  json "Team" as J {
    "id": "number",
    "name": "string",
    "locked": "boolean"
  }

"GET response \nURI: /api/teams/{teamId}" -> J 
@enduml