name: Generate PlantUML
on: 
  push:
    branches: [ "main" ]
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    permissions:
      contents: write
    env: 
      PLANTUML_JAR_PATH: docs/plantuml.jar
      DIAGRAM_PATH: docs
      OUTPUT_PATH: docs/Rendered
      COMMIT_MSG: ":rocket: adding generated diagrams"
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Process Class Diagrams
        run: java -jar ${{ env.PLANTUML_JAR_PATH }} -v -tsvg -r -o "${{ github.workspace }}/${{ env.OUTPUT_PATH }}/Class Diagrams" "${{ env.DIAGRAM_PATH }}/Class Diagrams/**.puml"
      - name: Process JSON Contracts
        run: java -jar ${{ env.PLANTUML_JAR_PATH }} -v -tsvg -r -o "${{ github.workspace }}/${{ env.OUTPUT_PATH }}/JSON Contracts" "${{ env.DIAGRAM_PATH }}/JSON Contracts/**.puml"
      - name: Process Use Case diagrams
        run: java -jar ${{ env.PLANTUML_JAR_PATH }} -v -tsvg -r -o "${{ github.workspace }}/${{ env.OUTPUT_PATH }}/Use Case Diagrams" "${{ env.DIAGRAM_PATH }}/Use Case Diagrams/**.puml"
      - name: Display Diagrams
        run: pwd && ls ${{ env.OUTPUT_PATH }}
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${{ env.COMMIT_MSG }}" || exit 0
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
