name: Generate PlantUML
on: 
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**.puml'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    permissions:
      contents: write
    env: 
      PLANTUML_JAR_PATH: docs/plantuml.jar
      DIAGRAM_PATH: docs/**.puml
      OUTPUT_PATH: docs/Rendered
      COMMIT_MSG: ":rocket: adding generated diagrams"
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Process Diagrams
        run: java -jar ${{ env.PLANTUML_JAR_PATH }} -v -tsvg -r -o "${{ github.workspace }}/${{ env.OUTPUT_PATH }}" "${{ env.DIAGRAM_PATH }}"
      - name: Display Diagrams
        run: pwd && ls ${{ env.OUTPUT_PATH }}
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${{ env.COMMIT_MSG }}" || exit 0
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
