name: Generate PlantUML
on: 
  push:
    paths:
      - '**.puml'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: docs/Rendered
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
